# Run locally with: goreleaser --rm-dist --snapshot --skip-publish
project_name: krateo
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X "main.Version={{.Version}}" -X "main.Build={{.ShortCommit}}"
    - -a -extldflags "-static"
  goos:
    - windows
    - linux
    - darwin
  goarch:
    #- arm
    - arm64
    - amd64
  goarm:
    - 7
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  -
    package_name: krateo
    vendor: Kiratech
    homepage: https://krateo.it/
    description: Run your Resources on Every Cloud
    license: Apache License 2.0
    maintainer: Kiratech
    formats:
      - deb
      - rpm

brews:
  - homepage: 'https://github.com/krateoplatformops/homebrew-krateo'
    description: 'Cross OS commandline tool to manage Krateo Platform.'
    folder: Formula
    commit_author:
      name: krateoplatformops
      email: projectkerberus@kiratech.it
    tap:
      owner: krateoplatformops
      name: homebrew-krateo
    install: |
      bin.install "krateo"

announce:
  twitter:
    enabled: false
    message_template: 'Krateo {{ .Tag }} is out! Check it out: https://github.com/krateoplatformops/krateo/releases/tag/{{ .Tag }}'

  discord:
    enabled: true
    message_template: 'Krateo {{ .Tag }} is out! Check it out: https://github.com/krateoplatformops/krateo/releases/tag/{{ .Tag }}'
    author: 'Krateo PlatformOps'
    icon_url: 'https://raw.githubusercontent.com/krateoplatformops/krateo/main/docs/media/avatar.png'
